ARG CLI_IMAGE
FROM ${CLI_IMAGE:-builder} as builder

FROM amazeeio/nginx
COPY lagoon/nginx.conf /etc/nginx/conf.d/app.conf

# Adding Stagefile helper
COPY lagoon/stagefile/stagefile-*.conf /etc/nginx/conf.d/

COPY --from=builder /app /app

ENV WEBROOT=web

RUN ls  /etc/nginx/conf.d/
